import { Controller } from "react-hook-form";

export const arLabels = {
    title: "عنوان",
    sub_title: 'العنوان الفرعي',
    description: 'وصف',
    main_image: 'الصورة الرئيسية',
    size: 'مقاس',
      bath_count: 'عد الحمام',
      bed_room_count: 'عدد غرف النوم',
      floor_type: 'نوع الكلمة',
      is_floor_available: 'الكلمة متاحة',
      additional_space_type:'نوع المساحة الإضافية',
      is_additional_space:'هي مساحة إضافية ',
      furnished_type: 'نوع الفرش',
      is_furnished:'مفروشة',
      revolution_date:'تاريخ الثورة',
      ceiling_height: 'ارتفاع السقف',
      is_ceiling: 'هو السقف',
      construction_year: 'السنة البناء',
      first_floor_map_image: 'صورة خريطة الطابق الأول',
      second_floor_map_image: 'صورة خريطة الطابق الثاني',
      address: 'يعرف',
      rating_count: 'عدد التصنيف',
      currency: 'عملة',
      price: 'سعر',
      has_heating: 'لديها التدفئة',
      heating_type: 'نوع التدفئة',
      has_window: 'لديه نافذة',
      window_type: 'نوع النافذة',
      has_air_conditioners: 'بها مكيفات',
      has_cable_tv: 'تحتوي على تلفزيون مع قنوات الكابل',
      has_fire_place: 'مدفأة غاز',
      has_intercorm: 'هكتار الاتصال الداخلي',
      has_wifi: 'لديه واي فاي',
      has_ventillation: 'لديه تهوية',
      has_garage: 'لديه مرآب',
      has_swimming_pool: 'يوجد حمام سباحة',
      has_parking: 'لديه موقف سيارات',
      has_garden: 'بها حديقة',
      school_distance: 'مسافة المدرسة',
      university_distance: 'مسافة الجامعة',
      hospital_distance: 'مسافة المستشفى',
      metro_station_distance: 'مسافة محطة المترو',
      grocery_center_distance: 'مسافة مركز البقالة',
      market_distance: 'مسافة السوق',
      gym_distance: 'مسافة الصالة الرياضية',
      river_distance: 'مسافة النهر',
      contact_no: 'رقم الاتصال',
      disabled_access_type: 'نوع الوصول معطل',
      fence_type: 'نوع السياج',
      security_camaras_count: 'عدد الكاميرات الأمنية',
      is_pet_friendly: 'صديق للحيوانات الأليفة',
      wellness_distance: 'مسافة العافية',
      _360_url: '360 رابط',
      sub_image_2: 'الصورة الفرعية 2',
      sub_image_1: 'الصورة الفرعية 1',
      map_url: 'للخريطة Url',
      video_url: 'رابط الفيديو',
};